Region.create(name: 'Middle East', code: 'me-south-1')
Region.create(name: 'India', code: 'ap-south-1')
Region.create(name: 'South America', code: 'sa-east-1')
Region.create(name: 'United States', code: 'us-east-1')
Region.create(name: 'Europe', code: 'eu-west-1' )
Region.create(name: 'Canada', code: 'ca-central-1 ')
Region.create(name: 'Japan', code: 'ap-northeast-1')
Region.create(name: 'Australia', code: 'ap-southeast-2')
Region.create(name: 'Asia Pacific', code: 'ap-southeast-1')
Service.create(name: 'Amazon CloudFront', code: 'AmazonCloudFront')